---
title: "Happiness_Project"
author: "Emma Horton"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
here::i_am("DataVisualization/dataviz_emma_testing.rmd")
```

Libraries

```{r}
library(dplyr)
library(ggplot2)
library(here)
library(readr)
library(tidyr)
library(plotly)
```

```{r}
here()
```

Read in Main Dataset, World Happiness 

```{r}
df <- here("Datasets")
happydf <- read.csv("HappyDataFrame.csv")
View(happydf)
str(happydf)
```

Read in Auxiliary Dataset, Population and Pre-Process
```{r}
df <- here("Datasets", "WorldBank_Population", "PopulationData.csv")
here()
population <- read_csv(df, skip = 4)
population <- population[, c(1:2, 50:(ncol(population) - 1))]

population <- population %>%
  rename(Country.Name = `Country Name`,Country.Code = `Country Code`)


View(population)
```

Gather Population Data
```{r}
population <- population %>%
  gather(key = "Year", value = "Population", -Country.Name, -Country.Code) %>%
    mutate(Year = as.integer(Year))
```

Attach Continents to Population
```{r}
#get unique countries from happydf
unique_countries <- happydf %>%
  select(Country.Name, Continent, Regional.Indicator) %>%
  distinct()

#decided to create new dataframe, ignore and delete later unless needed
#join population on country name
#population <- population %>%
  #inner_join(unique_countries, by = c("Country.Name" = "Country.Name"))

#View(population)
```

Join Population and Country Name Based on Year in New Set Happy Population

```{r}
happydf <- inner_join(happydf, population, by = c("Country.Name", "Year"))
#View(happydf)
```

Create First Draft
```{r echo=TRUE}
ggplot(happydf, aes(x = Year, y = Life.Ladder, color = Continent, shape = Continent)) +
  geom_jitter(alpha = 0.2) +
  geom_smooth()

```

Create Second Draft

```{r}
# Calculate scale
scaling_factor <- 0.0001 
happydf$RelativeSize <- happydf$Population * scaling_factor

ggplot(happydf, aes(x = Year, y = Life.Ladder, color = Continent, size = RelativeSize)) +
  geom_jitter(alpha = 0.2) +
  geom_smooth()

```


