# Import libraries
```{r}
library(dplyr)
library(ggplot2)
library(viridis)
library(ggridges)
library(data.table)
library(ggeasy)
```

# Import the data frame
```{r}
df <- read.csv("HappyDataFrame.csv")
View(df)
dim(df)
df <- df %>%
  filter(Continent != "Other")
```

```{r}
theme_set(theme_minimal())

mypalette <- c("royalblue", "forestgreen", "gold", "darkorange", "firebrick")
```

```{r}
by_continent <-
  df %>%
  group_by(Continent) %>%
  summarise(n=n(), Log.GDP.Per.Capita=mean(Log.GDP.Per.Capita, na.rm=TRUE))

df %>%
  ggplot(aes(x=Continent, y=Log.GDP.Per.Capita, color=Continent)) +
  geom_point(alpha = 0.1, position="jitter") +
  geom_point(data=by_continent, size=4) +
  geom_text(data=by_continent, aes(label=paste0("n=", n), y=5, color=NULL)) +
  scale_color_manual(values = mypalette) +
  labs("title" = "Distribution of GDP per Capita by Continent", y="GDP per Capita")
```

```{r}
df %>%
  ggplot(aes(y=Continent, x=Log.GDP.Per.Capita)) +
  geom_violin(aes(fill=Continent), alpha=0.5, color=NA, scale="area", show.legend=FALSE) + 
  geom_boxplot(aes(fill=NA), alpha=0.3, width=0.15, outlier.alpha=1, show.legend=FALSE) +
  scale_fill_viridis(discrete=TRUE) +
  labs("title" = "Distribution of GDP per Capita by Continent", x="GDP per Capita")
```
```{r}
df %>%
  filter(Continent=="Europe") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Europe", x="GDP per Capita")
```

```{r}
df %>%
  filter(Continent=="Americas") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Americas", x="GDP per Capita")
```

```{r}
df %>%
  filter(Continent=="Africa") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Africa", x="GDP per Capita")
```

```{r}
df %>%
  filter(Continent=="Asia") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Asia", x="GDP per Capita")
```
```{r}
df %>%
  ggplot(aes(Log.GDP.Per.Capita, Confidence.In.National.Government, color=Log.GDP.Per.Capita)) +
  geom_point() + 
  geom_smooth(lty=1, aes(col=Log.GDP.Per.Capita), span=0.005)
```

```{r}
df %>%
  ggplot(aes(Log.GDP.Per.Capita, fill=as.factor(Regional.Indicator))) + geom_histogram(col="white")
```

```{r}
ggplot(df, aes(Log.GDP.Per.Capita, 
                      alpha=Log.GDP.Per.Capita, 
                      y = as.factor(Regional.Indicator),
                      fill=as.factor(Regional.Indicator))) +
  geom_density_ridges(alpha=0.4, 
               adjust=0.05, 
               position="identity", show.legend=FALSE) +
    scale_alpha_continuous()
```

```{r}
world.map <- map_data(map = "world")

setnames(world.map, "region", "Country.Name")

unique_world_map <- unique(world.map$Country.Name)
unique_df <- unique(df$Country.Name)

# Names in df that do not match names in world.map
names_not_in_world_map <- setdiff(unique_df, unique_world_map)
print(names_not_in_world_map)

# Change the names to match df
world.map <- world.map %>%
  mutate(Country.Name = replace(Country.Name, Country.Name == "USA", "United States")) %>%
  mutate(Country.Name = replace(Country.Name, Country.Name %in% c("Democratic Republic of the Congo", "Republic of Congo"), "Congo (Brazzaville)")) %>%
  mutate(Country.Name = replace(Country.Name, Country.Name == "UK", "United Kingdom"))

df <- df %>%
  mutate(Country.Name = replace(Country.Name, Country.Name %in% c("Hong Kong S.A.R. of China", "Taiwan Province of China"), "China"))

world.map <- merge(world.map, df, by="Country.Name")

world.map <- world.map[order(world.map$order),]

ggplot(world.map, aes(long, lat, group=group)) +
  geom_polygon(aes(fill=Life.Ladder)) +
  coord_quickmap() +
  theme_void() +
  scale_fill_viridis(option="E", name="Index") +
  theme(legend.position='bottom') +
  labs(title="Happiness Index across the World") +
  ggeasy::easy_center_title()
View(world.map)
```

