libraries
```{r}
library(dplyr)
library(ggplot2)
```

```{r}
df <- read.csv("../../DataAnalysis/DataFramesCreated/whi.df.clean.csv")
```

Calculate linear regression
```{r}
linear_regression <- function(x, y, data) {
  formula <- as.formula(paste(y, "~", x))

  regression <- lm(formula, data = data)

  intercept <- coef(regression)[1]
  slope <- coef(regression)[2]
  r_squared_percentage <- round(summary(regression)$r.squared * 100, 1)
  
  return(list(intercept=intercept, 
              slope=slope, 
              r_squared_percentage=r_squared_percentage))
}
```

World happiness for years 2016 to 2020
```{r}
mean.happiness.before.covid <- df %>%
  filter(Year > 2015 & Year < 2021 ) %>%
  group_by(Year) %>%
  summarise(Life.Ladder = mean(Life.Ladder, na.rm = TRUE))

equation.before.covid = linear_regression("Year", "Life.Ladder", mean.happiness.before.covid)

happiness.regression.before.covid <- mean.happiness.before.covid %>%
  ggplot(aes(Year, Life.Ladder)) +
  geom_line(color = "gold") +
  geom_point(size=3, alpha=0.5, color = "gold") +
  geom_smooth(method='lm', color = "red", fill="gray90", se = TRUE, size=0.6) +
  labs(title="Average World Happiness", 
       subtitle=paste("Years: 2016 to 2020", "\nRegression Equation: Happiness = ", round(equation.before.covid$intercept, 2), '+ (', round(equation.before.covid$slope, 2), " * Year)", "\nR^2 =", equation.before.covid$r_squared_percentage, "%"), 
       x="\nYear", 
       y="Happiness Index") +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2000, 2020, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

happiness.regression.before.covid
```

Predicted world happiness for years 2020 to 2022
```{r}
years <- c(2021, 2022)
n <- length(years)
happiness.index <- numeric(n)
for (i in 1:n){
  happiness <- equation.before.covid$intercept + equation.before.covid$slope * years[i]
  happiness.index[i] <- happiness
}

predicted.happiness.df <- data.frame(Year = years, Life.Ladder = happiness.index)
predicted.happiness.df <- rbind(predicted.happiness.df, data.frame(Year = 2020, Life.Ladder = 5.727539))

happiness.predicted <- predicted.happiness.df %>%
  ggplot(aes(Year, Life.Ladder)) +
  geom_line(color = "firebrick") +
  geom_point(size=3, alpha=0.5, color = "firebrick") +
  labs(title="Predicted World Happiness", 
     subtitle=paste("Years: 2020 to 2022", "\nBased on Regression Equation: Happiness = ", round(equation.before.covid$intercept, 2), '+ (', round(equation.before.covid$slope, 2), " * Year)"),
     x="\nYear", 
     y="Happiness Index") +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2020, 2023, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

happiness.predicted
```

```{r}
happiness.predicted.all <- predicted.happiness.df %>%
  ggplot(aes(Year, Life.Ladder)) +
  geom_line(color = "firebrick") +
  geom_point(size=3, alpha=0.5, color = "firebrick") +
  geom_line(data=mean.happiness.before.covid, aes(Year, Life.Ladder), color = "gold") +
geom_point(data=mean.happiness.before.covid, aes(Year, Life.Ladder), size=3, alpha=0.5, color = "gold") +
  labs(title="Predicted World Happiness", 
     subtitle=paste("Years: 2016 to 2022", "\nBased on Regression Equation: Happiness = ", round(equation.before.covid$intercept, 2), '+ (', round(equation.before.covid$slope, 2), " * Year)"),
     x="\nYear", 
     y="Happiness Index") +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2016, 2023, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

happiness.predicted.all
```

Actual world happiness for years 2020 to 2022
```{r}
mean.happiness.after.covid <- df %>%
  filter(Year > 2019) %>%
  group_by(Year) %>%
  summarise(Life.Ladder = mean(Life.Ladder, na.rm = TRUE))

equation.after.covid = linear_regression("Year", "Life.Ladder", mean.happiness.after.covid)

happiness.regression.after.covid <- mean.happiness.after.covid %>%
  ggplot(aes(Year, Life.Ladder)) +
  geom_line(color = "gold") +
  geom_point(size=3, alpha=0.5, color = "gold") +
  geom_smooth(method='lm', colour = "red", fill="gray90", se = TRUE, size=0.6) +
  labs(title="Actual World Happiness", 
       subtitle=paste("Years: 2020 to 2022", "\nRegression Equation: Happiness = ", round(equation.after.covid$intercept, 2), '+ (', round(equation.after.covid$slope, 2), " * Year)", "\nR^2 =", equation.after.covid$r_squared_percentage, "%"), 
       x="\nYear", 
       y="Happiness Index") +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2020, 2023, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

happiness.regression.after.covid
```

```{r}
mean.happiness.after.covid$type <- 'Actual'
predicted.happiness.df$type <- 'Predicted'

predicted.vs.actual <- ggplot() +
  geom_line(data = predicted.happiness.df, aes(Year, Life.Ladder, color = type)) +
  geom_point(data = predicted.happiness.df, aes(Year, Life.Ladder, color = type), size=3, alpha=0.5) +
  geom_line(data = mean.happiness.after.covid, aes(Year, Life.Ladder, color = type)) +
  geom_point(data = mean.happiness.after.covid, aes(Year, Life.Ladder, color = type), size=3, alpha=0.5) +
  labs(title="Predicted vs Actual World Happiness", 
       subtitle="Years: 2020 to 2022",
       x="\nYear", 
       y="Happiness Index") +
  scale_color_manual(name='', values = c("Predicted" = "firebrick", "Actual" = "gold")) +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2020, 2023, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

predicted.vs.actual
```

```{r}
actual.data <- df %>%
  filter(Year > 2015) %>%
  group_by(Year) %>%
  summarise(Life.Ladder = mean(Life.Ladder, na.rm = TRUE)) %>%
  mutate(type = 'Actual')

combined.df <- rbind(actual.data, predicted.happiness.df)
combined.df
predicted.vs.actual.all <- ggplot(combined.df, aes(Year, Life.Ladder, color = type)) +
  geom_line() +
  geom_point(size=3, alpha=0.5) +
  labs(title="Predicted vs Actual World Happiness", 
     x="\nYear", 
     y="Happiness Index") +
  scale_color_manual(name = "", values = c("Predicted" = "firebrick", "Actual" = "gold")) +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2015, 2023, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

predicted.vs.actual.all
```
