libraries
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(reshape2)
library(DataExplorer)
library(here)
library(tidyr)
library(dplyr)
library(plotly)
library(ggplot2)
library(graphics)
library(crosstalk)
```

```{r}
df <- read.csv("../../Datasets/MLRHappyDataFrame.csv")
View(df)
```

```{r}

WHO <- df %>%
  select(Country.Name,Regional.Indicator,Year, Life.Ladder, Continent, Avg_Daily_ICU_Occupancy_Per_Million, Avg_Daily_NewCases,Avg_Daily_Cumulative_Cases, Avg_Daily_ICU_Occupancy, Avg_Daily_NewDeaths, Avg_Daily_Cumulative_Death) %>%
  na.omit(df)

# Calculate Missing-ness
#missing_percent <- colSums(is.na(WHO)) / nrow(WHO) * 100
#print(missing_percent)

# Perform multiple linear regression on the  dataframe
MLR_who <- lm(Life.Ladder ~ Avg_Daily_NewCases+Avg_Daily_NewDeaths+Avg_Daily_ICU_Occupancy_Per_Million+Avg_Daily_Cumulative_Cases+Avg_Daily_ICU_Occupancy+Avg_Daily_Cumulative_Death, data = WHO)


#Get residuals
model_residuals = MLR_who$residuals

# diagnostic plots #YUHAN

par(mfrow = c(2, 2))  # grid for plots
#The histogram looks normal; hence we can conclude the normality with enough confidence.

hist(model_residuals)

# residuals vs. fitted values (check homoscedasticity)
plot(MLR_who, 1)

# Q-Q Plot (check for normality of residuals)
plot(MLR_who, 2)

# Cook's distance (check outliers)
plot(MLR_who, 5)

par(mfrow = c(1, 1)) #  plotting layout

```


#multicollinearity assumption check
```{r}
#install.packages("ggcorrplot")
library(ggcorrplot)
library(heatmaply)


# Remove the Y column and non-numeric
columns_to_exclude <- c("Life.Ladder", "Country.Name", "Regional.Indicator", "Continent", "Epi_Pandemic_Year")

reduced_data <- WHO[, !(names(WHO) %in% columns_to_exclude)]
reduced_data <- na.omit(reduced_data)

# Compute correlation at 2 decimal places
corr_matrix = round(cor(reduced_data), 2)
# Compute a matrix of correlation p-values
p.mat <- cor_pmat(reduced_data)


#View(corr_matrix)
# Compute and show the  result
corr.plot <- ggcorrplot(corr_matrix, hc.order = TRUE, type = "lower", outline.col = "white",  p.mat = p.mat)
ggplotly(corr.plot) #YUHAN

#We see values with >.8 correlation
high_correlations <- which(corr_matrix > 0.8 & corr_matrix < 0.99, arr.ind = TRUE)
correlation_values <- corr_matrix[high_correlations]
variable_names <- rownames(corr_matrix)[high_correlations[, 1]]
correlated_variable_names <- colnames(corr_matrix)[high_correlations[, 2]]

result <- data.frame(
  Variable1 = variable_names,
  Variable2 = correlated_variable_names,
  Correlation = correlation_values
)

print(result)

```


#YUHAN

See which performed better
```{r}
#MLR_who
summary(MLR_who)
```




#IGNORE
# Calculate linear regression (MLR) ( I was able to get this to work but not plot like you Hanna)
```{r}
mlr_regression <- function(x_vars, y_var, data) {
  formula <- as.formula(paste(y_var, "~", paste(x_vars, collapse = "+")))
  regression <- lm(formula, data = data)
  
  coefficients <- coef(regression)
  intercept <- coefficients[1]
  slopes <- coefficients[-1]
  
  r_squared_percentage <- round(summary(regression)$r.squared * 100, 1)
  
  return(list(intercept = intercept, slopes = slopes, r_squared_percentage = r_squared_percentage))
}

```

#IGNORE
World happiness for years 2016 to 2020 (WHO)
```{r}

#NO IDEA HOW TO USE THIS ( do i need to include all MLR variables?)
mean.happiness.before.covid <- WHO %>%
  filter(Year > 2015 & Year < 2021) %>%
  group_by(Year) %>%
  summarise(Life.Ladder = mean(Life.Ladder, na.rm = TRUE))

# predictors
x_vars <- c(
  "Year", 
  "Healthy.Life.Expectancy.At.Birth", 
  "Confidence.In.National.Government", 
  "Population",
  "Avg_Daily_ICU_Occupancy_Per_Million",
  "Avg_Daily_NewCases",
  "Avg_Daily_Cumulative_Cases",
  "Perceptions.Of.Corruption",
  "Avg_Daily_NewDeaths",
  "Avg_Daily_Cumulative_Death"
)

data_frame <- WHO 
y_var <- c("Life.Ladder")

# Regression
#equation.before.covid <- mlr_regression(x_vars, y_var, WHO)

# results
intercept <- equation.before.covid$intercept
slopes <- equation.before.covid$slopes
r_squared_percentage <- equation.before.covid$r_squared_percentage

# intercept/slope
cat("Intercept:", intercept, "\n")
cat("Slopes:", slopes, "\n")
cat("R-squared Percentage:", r_squared_percentage, "%\n")


# plt
happiness.regression.before.covid <- WHO %>%
  ggplot(aes(Year, Life.Ladder)) +
  geom_line(color = "gold") +
  geom_point(size = 3, alpha = 0.5, color = "gold") +
  geom_smooth(method = 'lm', color = "red", fill = "gray90", se = TRUE, size = 0.6) +
  labs(
    title = "Average World Happiness", 
    subtitle = paste("Years: 2016 to 2020", 
                     "\nRegression Equation: Happiness = ", 
                     round(intercept, 2), 
                     '+ (', paste(round(slopes, 2), collapse = " + "), " * Year)", 
                     "\nR^2 =", r_squared_percentage, "%"), 
    x = "\nYear", 
    y = "Happiness Index"
  ) +
  theme_minimal() +
  scale_x_continuous(breaks = seq(2000, 2020, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0))

happiness.regression.before.covid


```

#YUHAN

```{r}
happydf <- read.csv("../../Datasets/HappyDataFrame.csv")
happydf %>%
  plot_ly(x = ~Year, y = ~Life.Ladder) %>%
  add_boxplot(
    color = ~Life.Ladder,
    colorscale = 'Viridis', 
    boxpoints = 'outliers', 
    text = ~Regional.Indicator, 
    marker = list(
      symbol = 'circle',  
      color = ~Regional.Indicator  
    )
  ) %>%
  layout(
    title = "Life Ladder by Year",
    xaxis = list(title = "Year"), 
    yaxis = list(title = "Life Ladder")
  )
```


Correlation of Constructs:
#YUHAN
```{r}
column_names <- colnames(happydf)
column_names
# Remove the Y column and non-numeric
columns_to_exclude <- c("Life.Ladder", "Country.Name", "Regional.Indicator", "Continent", "Country.Code")

reduced_data <- happydf[, !(names(happydf) %in% columns_to_exclude)]
reduced_data <- na.omit(reduced_data)

# Compute correlation at 2 decimal places
corr_matrix = round(cor(reduced_data), 2)
# Compute a matrix of correlation p-values
p.mat <- cor_pmat(reduced_data)


#View(corr_matrix)
# Compute and show the  result
corr.plot <- ggcorrplot(corr_matrix, hc.order = TRUE, type = "lower", outline.col = "white",  p.mat = p.mat)
ggplotly(corr.plot) #YUHAN

#We see values with >.8 correlation
high_correlations <- which(corr_matrix > 0.8 & corr_matrix < 0.99, arr.ind = TRUE)
correlation_values <- corr_matrix[high_correlations]
variable_names <- rownames(corr_matrix)[high_correlations[, 1]]
correlated_variable_names <- colnames(corr_matrix)[high_correlations[, 2]]

result <- data.frame(
  Variable1 = variable_names,
  Variable2 = correlated_variable_names,
  Correlation = correlation_values
)

print(result)
```


