```{r}
library(dplyr)
library(ggplot2)
library(ggpubr)
```

```{r}
df <- read.csv("../../DataAnalysis/DataFramesCreated/whi.df.clean.csv")
```

```{r}
df_clean<- df[!is.na(df$Perceptions.Of.Corruption), ]

correlation <- round(cor(df_clean$Life.Ladder, df_clean$Perceptions.Of.Corruption),2)

world_perception <- df_clean %>%
  group_by(Country.Name) %>% 
  summarise(Life.Ladder = mean(Life.Ladder), Perceptions.Of.Corruption = mean(Perceptions.Of.Corruption)) %>%
  ggplot(aes(x = Perceptions.Of.Corruption, y = Life.Ladder)) +
  geom_point(alpha = 0.2, color = "gold") + 
  geom_smooth(method = "lm", color = "red", fill = "grey", se = TRUE) +
  labs(title = "Relationship between Perceptions of Corruption\nand Happiness Index Across the World",
       subtitle = paste("Correlation coefficient:", correlation),
       x = "Perceptions of Corruption", 
       y = "Happiness Index") +
  geom_text(aes(label = Country.Name), vjust = -1, size = 1.8, check_overlap = TRUE) +
  theme_minimal()

world_perception
```

```{r}
corruption_regression <- function(df, continent){
  df_clean<- df[!is.na(df$Perceptions.Of.Corruption), ] %>%
    filter(Continent==continent)

  correlation <- round(cor(df_clean$Life.Ladder, df_clean$Perceptions.Of.Corruption),2)

  corruption <- df %>%
    filter(Continent==continent) %>%
    group_by(Country.Name) %>% 
    summarise(Life.Ladder = mean(Life.Ladder), Perceptions.Of.Corruption = mean(Perceptions.Of.Corruption)) %>%
    ggplot(aes(Perceptions.Of.Corruption, Life.Ladder)) +
    geom_point(alpha=0.5, color="gold") + 
    geom_smooth(method = "lm", color = "red", fill = "grey", se = TRUE) +
    labs(title=continent, 
         subtitle = paste("Correlation coefficient:", correlation), 
         x="Corruption", 
         y="Happiness") +
    ggeasy::easy_center_title() +
    theme_minimal()
  return(corruption)
}

cor_america <- corruption_regression(df, "Americas")
cor_asia <- corruption_regression(df, "Asia")
cor_europe <- corruption_regression(df, "Europe")
cor_africa <- corruption_regression(df, "Africa")

combined_plot <- ggarrange(cor_america, cor_asia, cor_europe, cor_africa, ncol = 2, nrow =2, common.legend = TRUE, legend="bottom")

final_plot <- annotate_figure(combined_plot, top = text_grob("Relationship between Perceptions of Corruption\nand Happiness Index", face = "bold", size = 13))
final_plot
```

```{r}
top_happiness <- df %>%
  group_by(Country.Name) %>%
  summarise(Life.Ladder = mean(Life.Ladder, na.rm = TRUE), corruption = mean(Perceptions.Of.Corruption, na.rm = TRUE)) %>%
  arrange(desc(Life.Ladder)) %>%
  head(15)

top_perception <- top_happiness %>%
  ggplot(aes(corruption, Life.Ladder, color=Life.Ladder)) +
  geom_point(show.legend = FALSE) + 
  geom_smooth(method = "lm", color = "red", fill = "grey", se = TRUE) +
  labs(title = "Relationship between Perceptions of Corruption\nand Happiness Index", 
       subtitle="Top 15 Happiest Countries",
       x = "Perceptions of Corruption", 
       y = "Happiness Index") +
  geom_text(aes(label=Country.Name), color="black", vjust=-1, size=2.3) +
  theme_minimal()

top_perception
```

```{r}
low_happiness <- df %>%
  group_by(Country.Name) %>%
  summarise(Life.Ladder = mean(Life.Ladder, na.rm = TRUE), corruption = mean(Perceptions.Of.Corruption, na.rm = TRUE)) %>%
  arrange(Life.Ladder) %>%
  head(15)

low_perception <- low_happiness %>%
  ggplot(aes(corruption, Life.Ladder, color=Life.Ladder)) +
  geom_point(show.legend = FALSE) + 
  geom_smooth(method = "lm", color = "red", fill = "grey", se = TRUE) +
  labs(title = "Relationship between Perceptions of Corruption\nand Happiness Index", 
       subtitle="Top 15 Unhappies Countries",
       x = "Perceptions of Corruption", 
       y = "Happiness Index") +
  geom_text(aes(label=Country.Name), color="black", vjust=-1, size=2.3) +
  theme_minimal()

low_perception
```
