# Import libraries
```{r}
library(dplyr)
library(ggplot2)
library(viridis)
library(ggridges)
```

# Import the data frame
```{r}
df <- read.csv("HappyDataFrame.csv")
View(df)
```

```{r}
by_continent <-
  df %>%
  group_by(Continent) %>%
  summarise(n=n(), Log.GDP.Per.Capita=mean(Log.GDP.Per.Capita, na.rm=TRUE))

df %>%
  ggplot(aes(x=Continent, y=Log.GDP.Per.Capita, color=Continent)) +
  geom_point(alpha = 0.15, position="jitter") +
  geom_point(data=by_continent, size=4) +
  geom_text(data=by_continent, aes(label=paste0("n=", n), y=5, color=NULL)) +
  labs("title" = "Distribution of GDP per Capita by Continent", y="GDP per Capita")
```

```{r}
df %>%
  ggplot(aes(y=Continent, x=Log.GDP.Per.Capita)) +
  geom_violin(aes(fill=Continent), alpha=0.5, color=NA, scale="area", show.legend=FALSE) + 
  geom_boxplot(aes(fill=NA), alpha=0.3, width=0.15, outlier.alpha=1, show.legend=FALSE) +
  scale_fill_viridis(discrete=TRUE) +
  labs("title" = "Distribution of GDP per Capita by Continent", x="GDP per Capita")
```
```{r}
df %>%
  filter(Continent=="Europe") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Europe", x="GDP per Capita")
```

```{r}
df %>%
  filter(Continent=="Americas") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Americas", x="GDP per Capita")
```

```{r}
df %>%
  filter(Continent=="Africa") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Africa", x="GDP per Capita")
```

```{r}
df %>%
  filter(Continent=="Asia") %>%
  ggplot(aes(Log.GDP.Per.Capita, color=Regional.Indicator, fill=Regional.Indicator)) +
  geom_density(alpha=0.3) +
  labs("title" = "Asia", x="GDP per Capita")
```

