# Import libraries
```{r}
library(dplyr)
library(ggplot2)
library(viridis)
library(ggridges)
library(data.table)
library(here)
library(plotly)
library(maps)
library(ggeasy)
library(gapminder)
```

Set File Location, Get Top Directory
```{r}
here::i_am("DataVisualization/E_visualization.rmd")
```

# Import the data frame
```{r}
df <- here("Datasets", "HappyDataFrame.csv")
df <- read.csv(df)
View(df)
dim(df)
df <- df %>%
  filter(Continent != "Other")
```

```{r}
theme_set(theme_minimal())

mypalette <- c("royalblue", "forestgreen", "gold", "darkorange", "firebrick")
```


Bars on Violence
```{r}


```


Bars on Demonstration
```{r}


```


Table 
```{r}


```


# Emma's First Draft of a Bubble Plot, Will Switch to Plotly
Goals:
Timeline, moving bubbles that are scaled with relative population size and follow the life.ladder trajectory
```{r}
# Calculate scale
scaling_factor <- 0.0001 
df$RelativeSize <- df$Population * scaling_factor

ggplot(df, aes(x = Year, 
               y = Life.Ladder, 
               color = Continent, 
               size = RelativeSize)) +
  geom_jitter(
    alpha = 0.2, 
    position = position_jitterdodge(
      jitter.width = 0.3, 
      dodge.width =0.3),
    shape = 16) +
  geom_smooth()
```


```{r}
#slow down animation
# continent bubble, if you click on the them then you can click on, regions are then displayed
# facet wrap, ~continent 
#traces / trails for the continent bubbles over time
# Correlation matrix of happiness - remove label
# Visualization Top Low R

# Calculate scale
scaling_factor <- 0.0001 
df$RelativeSize <- df$Population * scaling_factor


fig <- df %>%
  plot_ly(
    x = ~Life.Ladder, 
    y = ~Social.Support,  
    size = ~Population, 
    color = ~Continent, 
    frame = ~Year, 
    text = ~Country.Name, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  )

fig <- fig %>%
  animation_slider(
    currentvalue = list(prefix = "YEAR ", font = list(color="red")),
  )
fig <- fig %>% animation_opts(
    1000, easing = "elastic", redraw = FALSE
  )
fig <- fig %>% animation_button(
    x = 1, xanchor = "right", y = 0, yanchor = "bottom"
  )

fig
```



```{r}
my_bar <- df %>%
  ggplot(aes(x = Continent, y = Life.Ladder, fill = Continent)) + 
  geom_bar(stat = "identity")
my_bar
```


```{r}
my_bar + coord_flip()

```

```{r}
my_bar + coord_polar()
```

```{r}
ggplot(data=df, aes(x=Life.Ladder, fill=Continent)) +
    geom_density(alpha=0.3)
```


```{r}
#countries with the largest Happiness of variability over time.
df %>%
    group_by(Country.Name) %>%
    summarise(sd=sd(Life.Ladder), IQR=IQR(Life.Ladder)) %>% 
    top_n(8) %>%
    arrange(desc(sd))
```


```{r}
df %>%
    group_by(Continent, Year) %>%
    summarise(Life.Ladder=median(Life.Ladder)) %>%
    ggplot(aes(x=Year, y=Life.Ladder, color=Continent)) +
     geom_line(size=1) + 
     geom_point(size=1.5)
```



```{r}
df %>%
    group_by(Continent, Year) %>%
    summarise(Life.Ladder=median(Life.Ladder)) -> sumyear


```

```{r}
ggplot(sumyear, aes(x=Year, y=Life.Ladder, color=Continent)) +
    geom_point(size=1.5) +
    geom_smooth(aes(fill=Continent), method="lm")
```

```{r}
plt <- ggplot(data=df,
              aes(x=Perceptions.Of.Corruption, y=Life.Ladder))
plt + geom_point(aes(color=Continent)) +
      geom_smooth(method="loess") +
      scale_x_log10()

```

```{r}
p <- ggplot(df, aes(Year, Life.Ladder)) 
p <- p + scale_x_log10()
p <- p + aes(col=Continent) + geom_point() + geom_smooth(lwd=2, se=FALSE)

p <- p + ggtitle("Happiness vs Perception of Corruption by Continent")
p <- p + xlab("Year") + ylab("Happiness")
p + theme_bw()

```






```{r}
fig <- df %>%
  plot_ly(
    x = ~Year, 
    y = ~Life.Ladder,  
    size = ~Population, 
    color = ~Continent, 
    frame = ~Year, 
    text = ~Country.Name, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  ) %>%
  group_by(Continent) %>%
  add_lines(
    x = ~Year, 
    y = ~Life.Ladder,
    color = ~Continent,
    showlegend = FALSE,
    line = list(shape = "spline", smoothing = 20)  # smooth parameter
  ) %>%
  ungroup() %>%
  animation_slider(
    currentvalue = list(prefix = "YEAR ", font = list(color="red")),
  ) %>%
  animation_opts(
    1000, easing = "elastic", redraw = FALSE
  ) %>%
  animation_button(
    x = 1, xanchor = "right", y = 0, yanchor = "bottom"
  )

fig

```

